### Numpy

1 - Utilize o método numpy.info para obter informações do método numpy.add.

In [3]:
import numpy as np
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15. 

In [108]:
l1 = list(range(0,16,1))
l1


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

3 - Converta a lista criada para um objeto do tipo numpy array.

In [109]:
l1_np = np.array(l1)
l1_np


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [8]:
l2 = np.arange(0, 16, 1)
l2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

5 - Utilize o array criado anteriormente para exibir o tipo de dado antes e após convertê-lo para um tipo float. Em seguida, converta novamente o array para um tipo de dado inteiro de 32 bits e exiba o tipo numérico  atual.

In [22]:
l3 = l2.astype(float)
print(l2.dtype, l3.dtype)
l3 = np.array([l2], dtype=np.int32)
l3.dtype

int32 float64


dtype('int32')

6 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [36]:
# Insira a resposta abaixo.

# Passo 1 
l3.shape

# Passo 2
l3 = l3.reshape(4,4)

# Passo 3
l3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

7 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [43]:
np.mean(l3)
np.median(l3)
np.std(l3)



4.6097722286464435

8 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [46]:
copia = l3*(-1)
copia

array([[  0,  -1,  -2,  -3],
       [ -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11],
       [-12, -13, -14, -15]])

9 - Realize os seguintes procedimentos:
1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.
2.  Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo. 
3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

In [65]:
# Passo 1
v = np.vstack((l3, copia))
v

# Passo 2

h = np.hstack((v, v))
h

# Passo 3

p = np.dstack((h, h, h))
p.shape


(8, 8, 3)

10 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [84]:
v[:, [2,3]] = 1
v

array([[  0,   1,   1,   1],
       [  4,   5,   1,   1],
       [  8,   9,   1,   1],
       [ 12,  13,   1,   1],
       [  0,  -1,   1,   1],
       [ -4,  -5,   1,   1],
       [ -8,  -9,   1,   1],
       [-12, -13,   1,   1]])

11 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [86]:
s = v + 2.5
s

array([[  2.5,   3.5,   3.5,   3.5],
       [  6.5,   7.5,   3.5,   3.5],
       [ 10.5,  11.5,   3.5,   3.5],
       [ 14.5,  15.5,   3.5,   3.5],
       [  2.5,   1.5,   3.5,   3.5],
       [ -1.5,  -2.5,   3.5,   3.5],
       [ -5.5,  -6.5,   3.5,   3.5],
       [ -9.5, -10.5,   3.5,   3.5]])

12 - Apresente uma contagem dos valores únicos que estão presentes no array criado na questão anterior. 
 
 Siga o seguinte template: "Quantidade de ocorrências do elemento {}: {}"

In [163]:
(x,y) = np.unique(s, return_counts=True)

for i in range(len(x)):
    print(f"Quantidade de ocorrências do elemento {x[i]}: {y[i]}")


Quantidade de ocorrências do elemento -10.5: 1
Quantidade de ocorrências do elemento -9.5: 1
Quantidade de ocorrências do elemento -6.5: 1
Quantidade de ocorrências do elemento -5.5: 1
Quantidade de ocorrências do elemento -2.5: 1
Quantidade de ocorrências do elemento -1.5: 1
Quantidade de ocorrências do elemento 1.5: 1
Quantidade de ocorrências do elemento 2.5: 2
Quantidade de ocorrências do elemento 3.5: 17
Quantidade de ocorrências do elemento 6.5: 1
Quantidade de ocorrências do elemento 7.5: 1
Quantidade de ocorrências do elemento 10.5: 1
Quantidade de ocorrências do elemento 11.5: 1
Quantidade de ocorrências do elemento 14.5: 1
Quantidade de ocorrências do elemento 15.5: 1


13 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [174]:
# Passo 1
t = np.full((4, 2), 8)

# Passo 2
i = np.identity(4)

# Passo 3
t1 = np.transpose(t)
f = t1.dot(i)
f

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.]])

14 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [183]:
# Passo 1
n1 = np.arange(25, 50, 1).reshape(5,5)

# Passo 2
n2 = np.linspace(0, 1, 5).reshape(5,1)

# Passo 3
np.hstack((n1,n2))

array([[25.  , 26.  , 27.  , 28.  , 29.  ,  0.  ],
       [30.  , 31.  , 32.  , 33.  , 34.  ,  0.25],
       [35.  , 36.  , 37.  , 38.  , 39.  ,  0.5 ],
       [40.  , 41.  , 42.  , 43.  , 44.  ,  0.75],
       [45.  , 46.  , 47.  , 48.  , 49.  ,  1.  ]])

15 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear. 

In [24]:
n3 = np.logspace(0, 1, 5).reshape(5,1)
n3

array([[ 1.        ],
       [ 1.77827941],
       [ 3.16227766],
       [ 5.62341325],
       [10.        ]])

16 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado. 

In [25]:
def border(x):
    x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
    print(x)
    
border(n3)

[[ 0.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          1.77827941  0.        ]
 [ 0.          3.16227766  0.        ]
 [ 0.          5.62341325  0.        ]
 [ 0.         10.          0.        ]
 [ 0.          0.          0.        ]]


17 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [205]:
n4 = np.random.randn(1, 36)
n4.max()
n4.min()
n4.mean()
n4.std()

array([[-0.9276207 ,  0.11528072,  1.42090858, -0.98809225, -0.77189219,
         0.22686536,  0.64683043, -1.48325686,  2.05728067,  1.4383635 ,
         0.25007917, -0.07436314, -0.36374886,  0.00566015, -1.57673375,
        -1.2332915 , -0.76121861,  1.61838214, -0.26097956,  1.17374582,
        -0.29408268,  0.30249368,  0.44836342,  0.50221015,  0.18428173,
        -0.3689155 , -1.06477505,  1.7649969 , -0.52192495, -0.70125303,
         0.59797769, -0.79875274, -0.1628895 , -1.08481243, -1.1090328 ,
        -1.2141421 ]])

18 - Crie uma matriz de dimensões (50,50) com valores aleatórios entre 0 e 1 (distribuição uniforme). Exiba as duas últimas linhas da matriz.


In [229]:
n5 = np.random.rand(50, 50).reshape(50,50)
n6 = n5[[48,49], :]
n6

array([[2.42939245e-01, 6.04632526e-01, 3.05042323e-01, 7.83618693e-01,
        2.23254379e-02, 3.02174741e-01, 2.90858615e-01, 5.67824866e-01,
        5.73142046e-01, 7.04959369e-01, 1.41955862e-01, 1.36892079e-01,
        1.90086067e-01, 8.75858340e-01, 1.90099994e-01, 2.51972618e-01,
        3.49070599e-02, 4.67108887e-01, 8.24125973e-01, 4.39333837e-01,
        6.59284401e-01, 7.04885362e-01, 7.45379498e-01, 9.65870079e-01,
        6.96422645e-01, 3.68867119e-02, 4.90085282e-01, 7.89990080e-02,
        8.86227204e-01, 7.80054973e-01, 7.75164786e-02, 4.81142833e-01,
        1.43730389e-01, 3.58476369e-01, 7.53442209e-01, 2.73182092e-01,
        1.13665783e-01, 3.40123329e-01, 9.56495587e-01, 4.46898028e-01,
        6.39579571e-01, 5.28410440e-01, 8.21366946e-01, 9.21065514e-01,
        4.48683571e-01, 7.67246832e-01, 7.76104763e-01, 1.98218774e-01,
        9.47001164e-01, 8.97607749e-01],
       [1.89752386e-02, 6.84160835e-01, 1.94573361e-02, 8.10878459e-01,
        4.51756738e-02,

19 - Utilize o array de números aleatórios anterior e apresenta a soma de cada coluna. Em seguida, apresente a soma de cada linha.

In [239]:
n7 = np.sum(n5, axis=1)
n8 = np.sum(n5, axis=0)
n7, n8

(array([24.44260227, 26.68911863, 29.97605516, 24.61293166, 27.64301047,
        21.75597316, 21.88305574, 25.07197211, 27.50333528, 23.96676982,
        22.95819305, 23.12562953, 26.08793739, 21.20515119, 23.02328602,
        26.95246517, 24.65828053, 27.44117737, 24.25782636, 29.30772042,
        22.88701629, 27.7358167 , 22.21592223, 24.45680148, 24.77927985,
        30.6111293 , 20.58645281, 24.99548789, 23.04436883, 23.24107323,
        28.07319239, 24.39022865, 27.05266935, 23.70956254, 27.45658281,
        26.34530664, 25.33337658, 24.77260726, 21.26064609, 24.58694412,
        25.00174116, 22.89103407, 26.67497166, 26.34666323, 26.38219535,
        23.26698277, 28.9258228 , 24.26156666, 24.88391216, 23.78103692]),
 array([25.11212659, 27.02636493, 25.60422542, 26.12638116, 23.49555513,
        23.04582073, 24.86037973, 27.55026147, 25.23749105, 24.8563991 ,
        23.96560971, 26.8061472 , 25.84574321, 19.92220343, 23.15901182,
        26.77084239, 26.02055688, 28.66511778, 26

20 - Escreve uma função que receba um array como entrada e uma probabilidade *p* entre 0 e 1.  Existe uma probabilidade *p* de que a função retorne o logaritmo do array, caso contrário o array original deve ser retornado. Teste a função utilizando o array da questão anterior. Dica: considere utilizar a biblioteca random do numpy.

In [30]:
aar = np.arange(1, 5, 1)
def prob(x):
    p = np.random.rand()
    if p >= 0.6:
        return x
    else:
        return np.logspace(x, 1, num = 1, endpoint=False)

prob(aar)

array([[   10.,   100.,  1000., 10000.]])

21 - Crie dois arrays de 30 elementos contendo números aleatórios entre 1 e 3. Utilize os dois arrays  para derivar um novo array contendo uma comparação entre os valores de forma a indicar True caso elementos em uma mesma posição apresentam o mesmo valor e False caso contrário. Dica: não é necessário utilizar uma estrutura de repetição.

Exemplo.:

*inputs*:

array([1,3,2])

array([1,2,2])

*output*:

array([True, False, True])

In [248]:
a1 = np.random.randn(1,3, 30)
a2 = np.random.randn(1,3, 30)

a3 = np.equal(a1, a2)
a3

array([[[False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False],
        [False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False],
        [False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,
         False, False, False]]])

22 - Compare os dois arrays acima de forma a retornar de uma única só vez um valor booleando indicando se todos os valores contidos em ambos os objetos são iguais.

In [249]:
a4 = np.array_equal(a1, a2)
a4


False

23 - Realize os seguintes procedimentos:

1. Crie um array com formato 5x5 contendo somente valores verdadeiros. 
2. Dado que se conhece o número de linhas e colunas do array, selecione aleatoriamente três coordenadas (pode haver repetição de coordenadas) e as transforme em False.
3. Crie um array de dimensionalidade 5x5 a partir de um intervalo com valores de 0 até 24.
4. Utilize o array booleano para indexar o array criado no passo anterior.

In [295]:
# Passo 1
a5 = np.ones((5, 5), dtype=bool)

# Passo 2
a5[[4],[2,3,4]] = False

# Passo 3
a6 = np.arange(0, 25, 1).reshape(5,5)

# Passo 4
a7 = a6[a5]
a7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])